[package]
name = "hexmapper"
version = "0.1.0"
authors = ["Siobhán Sterrett <siobhan.sterrett@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
iced = { version = "0.3", features = ["canvas"] }
euclid = "0.22"
